name: remote ssh command
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh admin@13.211.53.51 "echo 'Deployment successfull'"
