name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the files
      uses: actions/checkout@v4
      
    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Add SSH Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts
      env:
        SERVER_HOST: ${{ secrets.HOST_DNS }}

    - name: Deploy to Server
      run: |
        cd /var/www/html
        sudo git clone https://github.com/didiferdillah23/ci-cd-html.git
        cd ci-cd-html
      env:
        SSH_KNOWN_HOSTS: 22
