name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }}

    - name: Add SSH Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      env:
        SERVER_HOST: ${{ secrets.HOST }}

    - name: Deploy to Server
      run: |
        cd /var/www/html
        echo "Host name: $(hostname)"

        PUBLIC_IPV4=$(curl -s https://api.ipify.org?format=text)
        echo "Public IPv4 Address: $PUBLIC_IPV4"
          
        # List only directories
        echo "Folders in HTML directory:"
        ls
        # sudo git clone https://github.com/didiferdillah23/ci-cd-html.git
      env:
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
